import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import { useAccount } from 'wagmi'
import { mainnet, sepolia, baseSepolia } from '@wagmi/core/chains'
import Wrapper2 from "../components/Wrapper2"
import NFTBoxContainer from "../components/NFTBoxContainer"


export default function Home() {

  const { address, isConnecting, isConnected, isDisconnected } = useAccount()
  return (
    <div className="bg-zinc-900 min-h-screen" >
      <Head>
        <title>TreeVerse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex justify-evenly items-center">
        <Wrapper2 />
        {isConnected ? (
          <div>
            {baseSepolia ? (
              <div className="">
                <LotteryEntrance className="p-8" />
              </div>
            ) : (
              <div>{`Please switch to BASE Sepolia to see the Raffle...`}</div>
            )}
          </div>
        ) : (

          <div className="p-5 flex h-[700px] w-[700px] items-center justify-center">
            <div className="w-full max-w-2xl items-center justify-center bg-white border border-zinc-200 shadow dark:bg-zinc-950 dark:border-zinc-700">
              <div className="p-5 m-10">
                <div>
                  <h5 className="text-xl font-semibold tracking-tight text-gray-900 dark:text-white mb-3 tracking-widest">TreeVerse</h5>
                  <p className="leading-6 text-m text-gray-900 dark:text-white mb-4">TreeVerse is a limited-edition generative art collection on the Mint blockchain.
                    Using p5.js, it features a variety of intricate tree designs with unique traits.
                    <br></br> Each piece symbolizes a commitment to preserving the natural world, blending technology and nature in a seamless digital experience.
                    <br></br> TreeVerse offers a unique opportunity to own a digital representation of nature's beauty in the blockchain era.
                  </p>
                  <div className="text-xl font-semibold tracking-tight text-gray-900 dark:text-green-400 mb-2 tracking-widest">Please Connect to a Wallet</div>

                </div>
              </div>
            </div>
          </div>
        )}
      </div>
      <NFTBoxContainer />

      <footer className="bg-white shadow dark:bg-black mt-10 border-t border-t-zinc-700 flex flex-row">
        <div className="w-full max-w-screen-xl mx-auto p-4 md:py-8">
          <div className="sm:flex sm:items-center sm:justify-between">
            <span className="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
              <img src="https://i.ibb.co/bPMZbSf/team-rocket-logo-32.png" className="h-8" alt="RocketTeam Logo" />
              <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white tracking-widest pl-2">RocketTeam</span>
            </span>

          </div>
          <hr className="my-6 border-zinc-200 sm:mx-auto dark:border-zinc-700 lg:my-8" />
          <span className="block text-sm text-zinc-500 sm:text-center dark:text-white  tracking-widest">© 2024 RocketTeam. All Rights Reserved.</span>
        </div>
      </footer>
    </div>


  );
}
